### ISSUE TITLE
Add Update URI

### ISSUE THREAD

**Issue by afragen** [robertdevore/gallery-modals#1]
Hey Robert!

If you don’t want this plugin ever to be overwritten by something in dot org you can just add the following header. 

`Update URI: https://github.com/robertdevore/gallery-modals`

https://make.wordpress.org/core/2021/06/29/introducing-update-uri-plugin-header-in-wordpress-5-8/

**Comment by afragen** [comment]
Could add a `GitHub Plugin URI` for Git Updater integration 😉

**Comment by robertdevore** [comment]
Thanks @afragen I added the `Update URI` before releasing 🙏
